export type CorporateSponsor = {
  name: string
  imgSrc: string
  href: string
}

export const platinumSponsors = [
  {
    name: 'Geocaching',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/geocaching.png`,
    href: 'https://geocaching.com',
  },
  {
    name: 'MCTAF',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/mcvb.png`,
    href: 'https://www.visitmountaineercountry.com/grants/#Grant-Guidelines',
  },
]
export const goldSponsors = []
export const silverSponsors = []
export const bronzeSponsors = []

export const friends = [
  'Beafrog',
  'Troopbiz (Mark)',
  'chipper66',
  'neoncacher',
  'Mi_Morenita',
  'Data Wrangler',
  'OneKindWord',
  'susanc14',
  'Team Bear-Cat',
  'Team Maltese - Zoe',
  'Team Maltese - Daisy',
  'Team Maltese - Tammy',
  'Team Maltese - Bob',
  'BillHSKC',
  'Team_Conway',
  'LMNLanchot',
  'NPG/VAB/P17/TKMY',
  'Team Diznee',
  'wvhunter',
  'DNeedham & TNSteeler',
  'ThorScouts',
  'Jackson1551',
  'MileHiKansan',
  'Third Turtle',
  'littleblkdog',
  'GR8CACHERS',
  'Semmels123',
  'PilotKev13',
  'dukemartin',
  'Paintedwarrior',
  'Nov64',
  'f0t0m0m',
  'TeAmGWinchester',
  'Troopbiz (Cathy)',
  'Troopbiz (Dave)',
  'JenOvations',
  'DOBIEST',
  'SFC Soto, F',
  'PhMJ',
  'TrexM8s',
  'Krazy4Catz',
  'Electric Water Boy',
]

export const blackDiamondBackers = [
  'Beafrog',
  'FORK',
  'FORK',
  'PapaBuck47',
  'Buckeyecacher111',
  'TheCachingKs',
  'Troopbiz',
  'xandryyte',
  'neoncacher',
  'Mi_Morenita',
  'Data Wrangler',
  'OneKindWord',
  'The Snowdog',
  'emilyjen',
  'SouthernGrits',
  'Prydeland',
  'fairyhoney',
  'CRWILDWOOD',
  'CRWILDWOOD',
  'roamstheworld',
  'nittany dave',
  'Nunavut Taidy',
  'the hiking viking',
  'susanc14',
  'DeeWhoa',
  'VABreeze',
  'TheLF',
  'RDM07',
  'Seemyshell',
  "AL's Guide",
  'Always Lost 00',
  'Minnesota Boy',
  'maingray',
  'WV5_0',
  'LISA365',
  'Team Bear-Cat',
  'Steve-n-Kim',
  'q22q17',
  'Team Maltese - Bob',
  'Team Maltese - Tammy',
  'ColeCops',
  'A_Babe_In_The_Woods',
  'BillHSKC',
  'ACT75',
  'geoprof123',
  'SHIPWRECK99',
  'ASmiley4Ken',
  'ASmiley4Ken',
  'pharm_girl2004',
  'GmaGigi',
  'Team_Conway',
  'LMNLanchot',
  'pea0001',
  'TravelingGeek',
  'NPGlenn',
  'bahama97',
  'TrekMan42',
  'Spaceboymom',
  'A-JerseyThing',
  'mmacgown',
  'wvhunter',
  'MYMOMDOESDOPE247',
  'Sakiman LI/NY',
  'DNeedham',
  'TNSteeler',
  'ThorScouts',
  'railroad',
  'Babynubbins',
  'Eeyore16',
  'HappyF33t3',
  'Jackson1551',
  'Jackson1551',
  'Nolehawks',
  'MileHiKansan',
  'Third Turtle',
  'Postal17',
  'CJ4FISH',
  'JPWAVE',
  'littleblkdog',
  'Semmels123',
  'Jhonnybee',
  'PilotKev13',
  'GR8CACHERS',
  'GR8Caches',
  'glofaw411',
  'dukemartin',
  'Paintedwarrior',
  'Nov64',
  'RogueAirPirate',
  'Littlest.Hal2',
  'benlorma07',
  'f0t0m0m',
  'PawfiaMom',
  'ElectricCorgi',
  'PianoRob2110',
  'Sro88jr',
  'CherokeeThree',
  'KanDkiss',
  'B52DGunner',
  'Debpfe',
  'LadeeDJ',
  'TeAmGWinchester',
  'The_Gringo_Kid',
  'flamingo_girl',
  'CuriousGeorge59',
  'twizzot',
  'Troopbiz',
  'Troopbiz',
  'Chihuahuak94me',
  'FrappGirl',
  'MARBLEGUY',
  'VASteelCityGirl',
  'JenOvations',
  'Dejavu20',
  'Senselessinct',
  'peachy1276',
  'KingLeo1973',
  '~Bailey~',
  'WVU1963',
  'WVU1963',
  'yeema',
  'LeffertsFamily',
  'LeffertsFamily',
  'kpub66',
  "dwayne's addiction",
  "dwayne's addiction",
  'DOBIEST',
  'DR.D.',
  'GameForTravel',
  'SFC Soto, F',
  'Yira0707',
  'JK186',
  'ncmtnluver',
  'bugsfan',
  'PhMJ',
  'PhMJ',
  'peachy1276',
  'Needtoodance',
  'DSQUAREDD2',
  'Sagaries',
  'Looneybin',
  'WVKiwi',
  'NMtumbleweed',
  'Oilbear125',
  'TrexM8s',
  'Pyro1970',
  'Krazy4Catz',
  'Electric Water Boy',
  'Crazy_Cache_Lady',
  'Cat-in-the-hat',
]
