export type CorporateSponsor = {
  name: string
  imgSrc: string
  href?: string
}

export const platinumSponsors = [
  {
    name: 'Geocaching',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/geocaching.png`,
    href: 'https://geocaching.com',
  },
  {
    name: 'Mountaineer Country CVB',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/mcvb.png`,
    href: 'https://www.visitmountaineercountry.com',
  },
  {
    name: 'Monongalia County Commission',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/mon_commission.png`,
  },
  {
    name: 'Pathtags',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/pathtags.png`,
    href: 'https://www.pathtags.com',
  },
  {
    name: 'Martinsburg CVB',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/martinsburg_cvb.png`,
    href: 'https://www.TravelWV.com',
  },
  {
    name: 'Marion CVB',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/marion_cvb.png`,
    href: 'https://www.MarionCVB.com',
  },
  {
    name: 'Historic Boston GeoTour',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/bostontour.png`,
    href: 'https://www.historicbostongeotour.com/',
  },
  {
    name: 'Gilby GeoTour',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/gilby.png`,
    href: 'https://www.gilbygeotour.com/',
  },
  {
    name: 'Retired Monkey Challenge Trail',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/monkey.png`,
    href: 'https://www.retiredmonkey.com/',
  },
  {
    name: 'Explore Houma',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/explorehouma_200x200.png`,
    href: 'https://explorehouma.com',
  },
  {
    name: 'Geoswag / Oakcoins',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/geoswag.png`,
    href: 'https://geoswag.com/',
  },
  {
    name: "Dick's Sporting Goods",
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/dicks_200x200.png`,
    href: 'https://www.dickssportinggoods.com/',
  },
]

export const goldSponsors = [
  {
    name: 'Belmont County',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/belmont.png`,
    href: 'https://www.visitbelmontcounty.com',
  },
  {
    name: 'McClumsy',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/mcclumsy.png`,
    href: 'https://mcclumsy.com',
  },
]
export const silverSponsors = [
  {
    name: 'Blackwater Outdoor Adventures',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/boa.png`,
    href: 'https://www.blackwateroutdooradventures.com/',
  },
  {
    name: 'Team Maltese',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/maltese.png`,
    href: 'https://www.geocaching.com/p/?guid=2227f7b2-ff37-4847-a1a3-743405f02419&wid=1345141b-666e-4f6b-80ea-b5b36146f51d&ds=2',
  },
  {
    name: 'Mylan Park',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/mylanPark.png`,
    href: 'https://mylanpark.org',
  },
  {
    name: 'Crunch Time',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/crunchTime.png`,
    href: 'https://crunchtimewv.com',
  },
  {
    name: 'XSCAPE',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/xscape.png`,
    href: 'https://www.escape.cool',
  },
  {
    name: 'Space Coast Geo-Store',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/spacecoast.png`,
    href: 'https://spacecoastgeostore.com/',
  },
  {
    name: 'Cache Craft',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/cachecraft.png`,
    href: 'https://www.cachecraftnj.com/',
  },
  {
    name: 'Odyssey Gifts',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/odyssey.png`,
    href: 'https://www.odysseydragons.com/',
  },
  {
    name: 'Wizard 3D',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/wizard3d.png`,
    href: 'https://www.facebook.com/p/Wizard-3D-61556558757315/',
  },
  {
    name: 'Poky Dot',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/pokydot_200x193.png`,
    href: 'https://www.facebook.com/ThePokyDot/',
  },
]
export const bronzeSponsors = [
  {
    name: 'Heart of Civil War GeoTrail',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/heart_of_civil_war.png`,
    href: 'https://www.heartofthecivilwar.org',
  },
  {
    name: 'GeocacheTalk',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/gctalk.png`,
    href: 'http://geocachetalk.com/',
  },
  {
    name: 'Gears & Gadgets',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/gearsngadgets.png`,
    href: 'https://www.gadgetsgeo.com/',
  },
  {
    name: 'Cachly',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/cachly.png`,
    href: 'https://www.cachly.com/',
  },
  {
    name: 'NYGO',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/nygo.png`,
    href: 'https://en.wikipedia.org/wiki/New_York_(state)',
  },
  {
    name: 'CACHETHELINE',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/cachetheline.png`,
    href: 'https://www.youtube.com/channel/UCZ2CBS4upyqZlZza6b1z9og',
  },
  {
    name: 'Loving WV',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/loving.png`,
    href: 'https://www.lovingwv.com/',
  },
  {
    name: 'Wooden Nickel',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/woodenfiver.png`,
    href: 'https://woodennickelgeocoins.com/',
  },
  {
    name: 'ArtEdCrafted',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/artedcrafted.png`,
    href: 'https://artedcrafted.com/?srsltid=AfmBOoqdP0VtlTRXovNhnaer9STaEn_hF05BAqG-Yk5JPumDjkKZ1yfI',
  },
  {
    name: 'Artisinal',
    imgSrc: `${import.meta.env.BASE_URL}sponsors/icons/artisinal.png`,
    href: 'https://www.example.com/',
  },
]

export const friends = [
  'Beafrog',
  'Troopbiz (Mark)',
  'chipper66',
  'neoncacher',
  'Mi_Morenita',
  'Data Wrangler',
  'OneKindWord',
  'susanc14',
  'Team Bear-Cat',
  'Team Maltese - Zoe',
  'Team Maltese - Daisy',
  'Team Maltese - Tammy',
  'Team Maltese - Bob',
  'BillHSKC',
  'Team_Conway',
  'LMNLanchot',
  'NPG/VAB/P17/TKMY',
  'Team Diznee',
  'wvhunter',
  'DNeedham & TNSteeler',
  'ThorScouts',
  'Jackson1551',
  'MileHiKansan',
  'Third Turtle',
  'littleblkdog',
  'GR8CACHERS',
  'Semmels123',
  'PilotKev13',
  'dukemartin',
  'Paintedwarrior',
  'Nov64',
  'f0t0m0m',
  'TeAmGWinchester',
  'Troopbiz (Cathy)',
  'Troopbiz (Dave)',
  'JenOvations',
  'DOBIEST',
  'SFC Soto, F',
  'PhMJ',
  'TrexM8s',
  'Krazy4Catz',
  'Electric Water Boy',
  'Incomenet',
  'FLPirate & The Wench',
  'sduck',
  'Anonymous',
  'Anonymous',
  'ARealWhit',
  'railroad',
  'ghostrider2099',
  'HntA',
  'geowoulfe',
  'Sparticus06',
  'FORK (Sally)',
  'FORK (Leif)',
  'foomanjoo',
  'Joebids',
  'Jimbolaya!',
  'Eagleblazer',
  'TakeMeOutdoors',
  'PA Hawkeye',
  'igator210',
  'dagin',
  'Geocachers of LI',
  'OneKindWord',
  'Vip Adventurers',
  'Team_Conway',
  'dnacache',
  'WV5_0',
  'marlin01',
  'littleblkdog',
  'AuDball24',
  'LostandFound28',
  'peachy1276',
  'cokelover',
  'Chembrat',
  '2getherbetter',
  'poeanne',
  'Networkcacher',
  'AllThingsEarthCache',
  'Murr Dog',
  'RetiredGuy',
  'the wanderr',
  'Dustoff_YaYa',
  'ezra7_10',
  'yanksfanjeff03',
  'Anonymous',
  'Anonymous',
  'The Soto Clan',
  'Offspringin',
  'tela42499',
  'chihuahuak94me',
  '_JohnnyCache',
  '4SwansT',
  'Buckeyecacher111',
  'Data Wrangler',
  'Snotrocketjl',
  'Fishing Gal',
  'obarshay',
  'Sialis',
  'Bigguy14760',
  'Love2bAlive',
  'Better With SAGE',
  'APC2',
  'Chris K in Geauga',
  'leenie222',
  'nomad721',
  'Odyssey Gifts',
  'gearguru',
  'kevins2betsey',
  'Anonymous',
  'ElectricCorgi',
  'fam2go',
  'OwenfromKC',
  'Me & Bucky',
  'Cluehunter',
  'AThrillofTheHunt',
  'KingOfCrows',
  'Axlfire',
  'steelersrull',
  'emilyjen',
]

export const blackDiamondBackers = [
  'Beafrog',
  'FORK',
  'FORK',
  'PapaBuck47',
  'Buckeyecacher111',
  'TheCachingKs',
  'Troopbiz',
  'xandryyte',
  'neoncacher',
  'Mi_Morenita',
  'Data Wrangler',
  'OneKindWord',
  'The Snowdog',
  'emilyjen',
  'SouthernGrits',
  'Prydeland',
  'fairyhoney',
  'CRWILDWOOD',
  'CRWILDWOOD',
  'roamstheworld',
  'nittany dave',
  'Nunavut Taidy',
  'the hiking viking',
  'susanc14',
  'DeeWhoa',
  'VABreeze',
  'TheLF',
  'RDM07',
  'Seemyshell',
  "AL's Guide",
  'Always Lost 00',
  'Minnesota Boy',
  'maingray',
  'WV5_0',
  'LISA365',
  'Team Bear-Cat',
  'Steve-n-Kim',
  'q22q17',
  'Team Maltese - Bob',
  'Team Maltese - Tammy',
  'ColeCops',
  'A_Babe_In_The_Woods',
  'BillHSKC',
  'ACT75',
  'geoprof123',
  'SHIPWRECK99',
  'ASmiley4Ken',
  'ASmiley4Ken',
  'pharm_girl2004',
  'GmaGigi',
  'Team_Conway',
  'LMNLanchot',
  'pea0001',
  'TravelingGeek',
  'NPGlenn',
  'bahama97',
  'TrekMan42',
  'Spaceboymom',
  'A-JerseyThing',
  'mmacgown',
  'wvhunter',
  'MYMOMDOESDOPE247',
  'Sakiman LI/NY',
  'DNeedham',
  'TNSteeler',
  'ThorScouts',
  'railroad',
  'Babynubbins',
  'Eeyore16',
  'HappyF33t3',
  'Jackson1551',
  'Jackson1551',
  'Nolehawks',
  'MileHiKansan',
  'Third Turtle',
  'Postal17',
  'CJ4FISH',
  'JPWAVE',
  'littleblkdog',
  'Semmels123',
  'Jhonnybee',
  'PilotKev13',
  'GR8CACHERS',
  'GR8Caches',
  'glofaw411',
  'dukemartin',
  'Paintedwarrior',
  'Nov64',
  'RogueAirPirate',
  'Littlest.Hal2',
  'benlorma07',
  'f0t0m0m',
  'PawfiaMom',
  'ElectricCorgi',
  'PianoRob2110',
  'Sro88jr',
  'CherokeeThree',
  'KanDkiss',
  'B52DGunner',
  'Debpfe',
  'LadeeDJ',
  'TeAmGWinchester',
  'The_Gringo_Kid',
  'flamingo_girl',
  'CuriousGeorge59',
  'twizzot',
  'Troopbiz',
  'Troopbiz',
  'Chihuahuak94me',
  'FrappGirl',
  'MARBLEGUY',
  'VASteelCityGirl',
  'JenOvations',
  'Dejavu20',
  'Senselessinct',
  'peachy1276',
  'KingLeo1973',
  '~Bailey~',
  'WVU1963',
  'WVU1963',
  'yeema',
  'LeffertsFamily',
  'LeffertsFamily',
  'kpub66',
  "dwayne's addiction",
  "dwayne's addiction",
  'DOBIEST',
  'DR.D.',
  'GameForTravel',
  'SFC Soto, F',
  'Yira0707',
  'JK186',
  'ncmtnluver',
  'bugsfan',
  'PhMJ',
  'PhMJ',
  'peachy1276',
  'Needtoodance',
  'DSQUAREDD2',
  'Sagaries',
  'Looneybin',
  'WVKiwi',
  'NMtumbleweed',
  'Oilbear125',
  'TrexM8s',
  'Pyro1970',
  'Krazy4Catz',
  'Electric Water Boy',
  'Crazy_Cache_Lady',
  'Cat-in-the-hat',
  'Incomenet',
  'jellicle',
  'FLPirate',
  'The Wench',
  'Snowsox',
  'Desafio',
  'Nurse 1',
  'Samurai6',
  'Sasamichicken',
  'Shonda181',
  'Floridafinder2',
  'Team T.W.I.S.T.E.D.',
  'sduck',
  'anndancy',
  'georeyna',
  'FloridaJim',
  'Buckeyegrrl',
  'beekayroot',
  'Turtleladi1020nhubbs',
  'GS1720',
  'Pisac',
  'GArunner',
  'Crammerfamily',
  'TeamXMan',
  'MS.Blonde',
  'Pisac',
  'ProfessorZoom',
  'Cecil-EGCM',
  'balloop',
  'SKILLET',
  'effstop',
  'BnJBish',
  'fishgeek',
  'QUE3NBE3',
  'BLURRYFAC3',
  'renruts',
  'Dlinst84',
  'Crammerfamily',
  'Mitovirginia',
  'Mitovirginia',
  'Ksullivan',
  'Turrell2',
  'DrUnKiN mOnKeYs',
  'Bigguy14760',
  'Muskoka Pearl',
  'Scottish Cavalryman',
  'Buffalo113',
  'Fishigfool60',
  'Gugma',
  'jst4fun',
  'jst4fun',
  'SLAUGY',
  'Bea-frog',
  'Dbricks',
  'ARealWhit',
  'TNDuke',
  'Albedo_0.39',
  'HntA',
  'SpongeBob CachePants',
  'Slyann62',
  'SallySedona',
  'Sparticus06',
  'Vip Adventurers',
  'Pegasusmoon',
  'foomanjoo',
  'Joebids',
  'laci729',
  'CURIOUSKDB',
  'OneKindWord',
  'Hurricane 61',
  'Eagleblazer',
  'Edwards654',
  'HistoricalGourmet',
  'blue&violet',
  'Firetaz',
  'beans&franks',
  'CANTHAI',
  'Tman109ner',
  'Turkey819',
  'Igfrey',
  'Butterfly_TeamBnB',
  'simdeb14',
  'llatnek',
  'Winelegs',
  'dagin',
  'mjg231',
  'scurvy doggs',
  'yervel',
  'Daniel_Kaufmann',
  'LayneKaufmann',
  'oz8118',
  'dnacache',
  'dnacache',
  'SuzyJazz',
  'ThorScouts',
  'Lighthouse Puppets',
  'AuDball24',
  'Gene_Hunter',
  'HTBob',
  'Luckycharm95',
  'DanTheMan2448',
  'CarpenterLuvaKatCrew',
  'hunterKat',
  'ONESPIRIT555',
  'Norma627',
  'fairyhoney',
  'Cache Addict-mel',
  'BearWalker21',
  'Shalacknar',
  'Gonewiththewin',
  'sugarbabies12',
  'byonke',
  'den2den2',
  'FairWeatherCacher',
  'Skibug9',
  'Ohmom50',
  'Thelanes',
  'mathqtpi',
  'cokelover',
  'SmilingBee',
  'Strek2',
  '2getherbetter',
  'DVC1',
  'theghostcachers',
  'theghostcachers',
  'CamzJ',
  'Rooper3',
  'Piglet404',
  'BOHICA_Bear',
  'kevins2betsey',
  'kevins2betsey',
  "Scrappin'mama",
  'quadguy47',
  'Offspringin',
  'Mike463',
  'sasamichicken',
  'Timeage',
  'tigercash',
  'Lighthouse Puppets',
  'crystaloops',
  'CubmasterP351',
  'Allysmom24',
  'MJBinski',
  'topkitty98',
  'poeanne',
  'Nanahuck',
  'gslink (GTN co-host)',
  'Lock-Nest',
  'Networkcacher',
  'juan2jam',
  'e-r-h',
  'sjconnelly',
  'Diverrn',
  'eng78ine',
  'wvcachers3',
  'AllThingsEarthCache',
  'dennyandjan',
  'dennyandjan',
  'Puppydog',
  'En_Passant',
  'Thrilled2b',
  'Lostken',
  'Littlefox1968',
  'GeoDandrew',
  'makeme',
  'makeme',
  'green nikki',
  'Rancid13',
  'CacheMeOnTheRun',
  'SCIONWB',
  'Leafer54',
  'wvmikiepar',
  'RetiredGuy',
  'pmed69',
  'SydandtheKid77',
  'the wanderr',
  'JasoniusMaximus',
  'big315red',
  'Trio of fun',
  'MSTzilla',
  'NCRed67',
  'Frank&Michele',
  'Frank&Michele',
  'BansheeShadow',
  'Dustoff_YaYa',
  'PinkBiker81',
  'Dirtytrails',
  'Wirtz',
  'charchoc',
  'Undertaker54andwife',
  'Undertaker54andwife',
  'grandmabetsy',
  'Hank15',
  'BinderyGuy',
  'ezra7_10',
  'pbump',
  'UBAD',
  'ladyrdr',
  'jbopto',
  'Jecepe08',
  '_JohnnyCache',
  'lonewolff15',
  'Tobydawgz',
  'CaptainMath',
  'CulinaryGirl13',
  'TheLePews',
  'GJ3M',
  'Staticbird11',
  'GeoTurtle2311',
  'JoenGPS',
  'yanksfanjeff03',
  'MrBeesTravels',
  'Gnomey Yo',
  'TexasTechBrat',
  'Guido O',
  'gearguru',
  'Lindy4',
  'DUDLEYGRUNT',
  'StandingBy1',
  'AdamBA',
  'MARSHALL',
  'MarkyMark66',
  'GeoAddictz',
  'M6216',
  'Baxtersnooper',
  'TeamPK',
  'Nite Owl',
  '3Woofs',
  '3Woofs',
  'Moontwig',
  'brikrambo',
  'Tyva28',
  'Misfit+1',
  'Jonny Rascal',
  'Rascal’s Wife',
  'Tallahassee-Lassie',
  'Rfyooper88',
  'SP4FUN',
  'bbatch6',
  'GeoTribeFive',
  'GOGC09',
  'moocher2notyou',
  'WhiskeySowers',
  'nomad721',
  'nomad721',
  'USAF MSgt',
  'smithdk',
  'CptHappyfeet94',
  'Nascar Nut',
  'Sharon12',
  'mikes_1999',
]
